spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PWD}"
    driver-class-name: "org.postgresql.Driver"
  flyway:
    enabled: true

server:
  port: 5000