name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Check with Gradle
      run: gradle clean build

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
        application_name: CostControllerApplication
        environment_name: Costcontrollerapplication-env
        version_label: 12345
        region: eu-west-1
        deployment_package: build/libs/cost-controler-0.0.1-SNAPSHOT.jar
